---
- name: "update apt packages."  # sudo apt upgrade
  become: true
  apt:
    update_cache: true
    upgrade: true

- name: remove uneeded dependencies  #sudo apt autoremove
  become: true
  apt:
    autoremove: true

- name: "install dependencies."   #sudoapt install nodejs npm
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: true

- name: "install pm2"   #sudo npm install pm2 -g
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: latest
